### ISSUE TITLE
MainActivity todo list

### ISSUE THREAD

**Issue by gunhoo** [PickPic/PickPic_Client#5]
- [x]  complete directory listview

- [x]  complete date gridview

- [x]  complete tag listview
